development: &base
  database: consensus_development
  adapter: postgresql
  host: localhost
  username: <%= ENV["CONSENSUS_PG_USERNAME"] || "postgres" %>
  password: <%= ENV["CONSENSUS_PG_PASSWORD"] || "postgres" %>
  pool: 5

test:
  <<: *base
  database: consensus_test
